config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ブックモデルのルーティング
  # ブックコントローラ
  resources :books, only: [:edit, :create, :index, :show, :update, :destroy]

  # # ホームのコントローラ
  root "homes#top"
  get "home/about" => "homes#index"


  # ユーザーモデルのルーティング
  # ユーザーコントローラ
  resources :users, only: [:show, :edit, :update, :index]
  
  # サーチアクション
  get "search" => "search#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # 検索メソッド
  def self.search(search_text,select_model,select_part)
    if select_part == "perfect"
      @books = Book.where(title: search_text)
    elsif select_part == "front"
      @books = Book.where("title LIKE?","#{search_text}%")
    elsif select_part == "back"
      @books = Book.where("title LIKE?","%#{search_text}")
    elsif select_part == "partial"
      @books = Book.where("title LIKE?","%#{search_text}%")
    else
      @books = Book.all
    end
  end

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { in: 1..200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  # 検索メソッド
  def self.search(search_text,select_model,select_part)
    if select_part == "perfect"
      @users = User.where(name: search_text)
    elsif select_part == "front"
      @users = User.where("name LIKE?","#{search_text}%")
    elsif select_part == "back"
      @users = User.where("name LIKE?","%#{search_text}")
    elsif select_part == "partial"
      @users = User.where("name LIKE?","%#{search_text}%")
    else
      @users = User.all
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  # ログインしたあとに飛ぶページの設定
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
    redirect_to book_path(@book.id), notice: "本を投稿"
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.id != current_user.id
      redirect_to books_path
    end
  end

  def show
    @book = Book.find(params[:id])
    @new = Book.new
    @user = current_user


  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "更新しました"
   else
     render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "削除しました"
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    search_text = params[:search_text]
    @select_model = params[:select_model]
    select_part = params[:select_part]
    @books = Book.search(search_text,@select_model,select_part)
    @users = User.search(search_text,@select_model,select_part)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path, notice: "更新しました"
    else
     render :edit
    end

  end


  private
  def user_params
     params.require(:user).permit(:profile_image, :name, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/seach_helper.rb
module SeachHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
 <!--投稿部分-->
<h1>New book</h1>
<!-- form_with部分 -->
<%= form_with model:book, local:true do |f| %>
<h4>タイトル</h4>
<%= f.text_field :title, placeholder: "タイトル" %>
<h4>内容</h4>
<%= f.text_area :body, placeholder: "内容" %></br>
<%= f.submit '本の投稿', class: "btn btn-info active" %>
<% end %>

app/views/books/edit.html.erb
<!--編集画面-->

<div class="notice">
  <%= notice %>
</div>

<!--エラー文章部分-->
<div class="error">
<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>error</h2>
    <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>
</div>

<h1>Editing Book</h1>
<%= form_with model:@book, url: book_path(@book.id), local:true do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book', class:"btn btn-info active" %>
    <%= link_to "Show", book_path(@book.id), class: "btn btn-info active" %>
    <%= link_to "Back", books_path,  class: "btn btn-info active" %>
<% end %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="notice">
      <%= notice %>
    </div>
    <!--エラー部分-->
    <%= render "layouts/error", book: @book %>
    <div class="col-xs-3">
      <!--ユーザー情報部分-->
      <%= render "users/user", user: @user %>
      <!--フォーム部分-->
      <%= render "form", book: @book %>
    </div>
    <div class="col-xs-9">
      <!--一覧部分-->
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
              <% end %>
            </td>
            <td><%=  link_to book.title, book_path(book.id) %></td>
            <td><%=  book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--詳細ページ-->
<!--エラー部分-->
<%= render "layouts/error", book: @new %>
<div class="container">
    <div class="row">
        <div class="notice">
          <%= notice %>
        </div>
        <div class="col-xs-3">
            <!--ユーザー情報部分-->
            <%= render "users/user", user: @book.user %>
            <!--フォーム部分-->
      　　　　<%= render "form", book: @new %>
        </div>
        <div class="col-xs-9">
            <!--本の詳細部分-->
            <h1>Book detail</h1>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book.user.id) do %>
                                <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
                                </br>
                                <%= @book.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <!--タイトル-->
                            <p><%= link_to @book.title, book_path(@book.id) %></p>
                        </td>
                        <td>
                            <!--オピニオン-->
                            <p><%= @book.body %></p>
                        </td>
                    <!--もしログインしてるユーザーと投稿した人が一致していたら表示できる-->
                    <% if @book.user == current_user %>
                        <td>
                         <%= link_to "Edit", edit_book_path(@book.id),  class: "btn btn-info active" %>
                        </td>
                 　  　　<td>
                　        <%= link_to "Destroy", book_path(@book.id), class: "btn btn-default", method: :delete, "data-confirm" => "本当に消しますか？?" %>
                　   　  </td>
                    <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/homes/index.html.erb
<!--aboutページ-->

<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>

app/views/homes/top.html.erb
<!--ログインする前のページ-->
<!--トップページ-->
<div class="notice">
  <%= notice %>
</div>

<div class="container">
  <div class="row">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
    <h2>
      In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,<br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    about various books!
    </h2>
    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to "log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<!--エラー文章部分-->
<div class="error">
    <% if book.errors.any? %>
        <h2><%= book.errors.count %>件のエラーが発生しました。</h2>
        <ul>
            <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <div class="hana">
              <span>Bookers</span>
          </div>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to "Users", users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book" %></li>
              <li><%= link_to "logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %></li>
            <% else %>
              <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to "About", home_about_path, class: "glyphicon glyphicon-link" %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
      <div class="row">
        <div class="col-xs-12">
          <!--検索フォーム-->
          <% if user_signed_in? %>
            <div style="margin-top: 55px" >
              <%= form_with url: search_path, method: :get, local: true do |f| %>
              <%= f.text_field :search_text, placeholder: "ここで検索" %>
              <%= f.select :select_model,[["BOOK","book_title"],["USER","user_name"]], include_blank: "選択して下さい" %>
              <%= f.select :select_part,[["完全一致","perfect"],["前方一致","front"],["後方一致","back"],["部分一致","partial"]], include_blank: "選択して下さい" %>
              <%= f.submit  "検索", class: "btn btn-info active" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <div style="margin-top: 51px;">
      <%= yield %>
    </div>

    <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
         CopyRight Infratop.inc
        </div>
      </div>
    </div>
    </footer>
  </body>
</html>

app/views/search/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>検索結果</h1>
      <table class="table">
        <% if "book_title" == @select_model %>
        <thead>
          <tr>
          <th>画像</th>
          <th>タイトル</th>
          <th>内容</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
            </td>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
        <% else %>
        <thead>
          <tr>
          <th>画像</th>
          <th>名前</th>
          <th>自己紹介</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
            </td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
          </tr>
          <% end %>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<!--マイページ表示部分-->
<h1>User info</h1>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
<table class="table">
  <tr>
    <th>名前</th>
    <th><%= user.name %></th>
    <th></th>
  </tr>
  <tr>
    <th>自己紹介</th>
    <th><%= user.introduction %></th>
    <th></th>
  </tr>
</table>
<button type="button" class="btn btn-default" aria-label="Left Align"><%= link_to '', edit_user_path(current_user.id), class: "glyphicon glyphicon-wrench" %></button>

app/views/users/edit.html.erb
<!--エラー文章部分-->
<% if @user.errors.any? %>
  <h2><%= @user.errors.count %>error</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<!--ユーザー情報編集ページ-->
<h1>User info</h1>
<%= form_with model:@user, local:true do |f| %>
  <h2>Name</h2>
  <%= f.text_field :name %>
  <h2>Image</h2>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  <h2>Introduction</h2>
  <%= f.text_area :introduction %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<!--登録したアカウント一覧ページ-->

<div class="container">
  <div class="row">
    <div class="col-xs-3">
       <!--ユーザー情報部分-->
       <%= render "user", user: @user %>
       <!--フォーム部分-->
       <%= render "books/form", book: @book %>
    </div>

    <div class="col-xs-9">
     <h1>Users</h1>
      <table class="table">
        <!--登録したアカウントの一覧部分-->
          <thead>
            <tr>
              <th>画像</th>
              <th>名前</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id), class: "btn btn-info active" %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!--ホームページ（HOME）-->
<div class="container">
  <div class="row">
    <!--成功文章-->
　<p><a href="#" class="text-success"><%= notice %></a></p>
    <div class="col-xs-3">
      <!--ユーザー情報部分-->
       <%= render "user", user: @user %>
      <!--フォーム部分-->
      <%= render "books/form", book: @book %>
    </div>


    <div class="col-xs-9">
      <!--一覧部分-->
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>内容</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %>
              <% end %>
            </td>
            <td><%=  link_to book.title, book_path(book.id) %></td>
            <td><%=  book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>